### ISSUE TITLE
Should it support files with empty last line?

### ISSUE THREAD

**Issue by jpagex** [BrianHicks/elm-csv#8]
I do not know if this would be desirable, but at the moment, if the file has the last line empty, there is an error like:
```
There was a problem on row -1: I looked for a column named `Population`, but couldn't find one.
```

SSCCE (Short Self-Contained Correct Example):
```elm
decodeCustom
    { fieldSeparator = '\t' }
    FieldNamesFromFirstRow
    (map2 Tuple.pair
        (field "Country" string)
        (field "Population" int)
    )
    "Country\tPopulation\nArgentina\t44361150\nBrazil\t212652000\n"
    |> Result.mapError errorToString
```

If I remove the last `\n` it works fine.

Is this feature desirable or should we make sure the files do not have an empty line at the end?

**Comment by BrianHicks** [comment]
ah, no, that's a bug. Thanks for bringing it up!

**Comment by BrianHicks** [comment]
also, wow, sorry about that error message 🙈
